### ISSUE TITLE
Failure to plot more than 16384 points

### ISSUE THREAD

**Issue by KevinPoole** [spectriclabs/sigplot#12]
Hi Sigplot team,

I am investigating an issue right now where Sigplot refuses to plot more than 16384 points (I am running in XY mode). I am going to continue to investigate, but if anyone on your side has any insight here in the meantime I would greatly appreciate it.

-Kevin

**Comment by kmun** [comment]
I am just a user, but I am able to display over 1.6 million points in 1D.  In 2D mode I can display 60,000 wide by 200 as a static raster.  I do have an older version of sigplot.  This may not be helpful since I'm not displaying in XY (not sure what XY mode is, unless that's for a surface).

**Comment by KevinPoole** [comment]
Hey thanks for your engagement @kmun - yeah, sadly I have a feeling it is specific to my use of XY mode which allows for non-static xdelta (aka, arbitrary plotting of XY points)

**Comment by KevinPoole** [comment]
I found that I was always ending up in this case:
- https://github.com/spectriclabs/sigplot/blob/main/js/sigplot.layer1d.js#L264

So as new data was loaded it was never actually going and getting new data into and from the buffers.

The below (hacky feeling) change seemed to get me past that:
```
            if ((this.mode !== 'XY') && (imin >= this.imin) && (imin + npts <= this.imin + this.size) && (this.ybuf !== undefined)) {
                // data already in buffers
            }
```

by preventing me from dropping into that case while in XY  mode. But then the next boundary I seem to run into is at `32768` points with everything beyond that being cut off.

Will continue digging, but any and all help / comments are welcome!

**Comment by KevinPoole** [comment]
I am assuming this comment is relevant here, but I can not determine where / how this referenced behavior is enforced in code:
https://github.com/spectriclabs/sigplot/blob/fa92189585cdc2daf0ea8de374ab48a5f8f214c2/js/sigplot.js#L8833

**Comment by KevinPoole** [comment]
wellp. not sure if it is the _**best**_ way to solve my issue but I just upped `options.bufmax` to `1e5` and then it worked 🤷‍♂️
