### ISSUE TITLE
Layer1D reload issues when zoomed in

### ISSUE THREAD

**Issue by thezboe** [spectriclabs/sigplot#15]
**Describe the bug**
A Layer1D that is constantly updating with live data does not update anymore after zooming in.

**To Reproduce**
Create a plot with a 1D layer
Create a timer that periodically reloads the layer with new *different* data
Zoom in with the mouse
Observe that the plot stops updating with new data as it was before zooming

**Expected behavior**
The data should update as expected, just within the new view

**Desktop (please complete the following information):**
 - OS: Windows, Linux
 - Browser Chrome, Firefox

**Additional context**
This problem seems to have been introduced with this changeset:
https://github.com/spectriclabs/sigplot/commit/c189bbdd70cabf25c91d9ac4a410572e511f76ee#diff-2b0543c268ad9b4ac5d7438fa444f512d0871a2836ee0f64f03f6dfb999af52fL328-R339

Adding the line `ybuf=undefined` seems to fix the issue so that the following statement doesn't resolve to true:
https://github.com/spectriclabs/sigplot/blob/2f684ae55044ee27ba70d7d519af597e5382fe4a/js/sigplot.layer1d.js#L263

**Comment by maihde** [comment]
The `this.ybuf undefined` has been included so closing this issue.
