### ISSUE TITLE
Reloading a plot layer with new data fails if number of data points exceed bufmax

### ISSUE THREAD

**Issue by EighthOctave** [spectriclabs/sigplot#17]
**Describe the bug**
The default bufmax is 2^15.  If an array's size exceeds this, the first call to reload for a 1d layer renders fine.  However, subsequent calls to reload fail to rerender the plot.  No errors are thrown.

**To Reproduce**

1. Create an array of 2^15+1 random values.
2. Create a plot with a single 1d layer. Plot's bufmax should be the default 2^15.
3. Call reload on the plot for this layer with the array of random values.
4. Regenerate the array in step 1 with new random values
5. Call reload again with the new array
6. Plot does not update

**Expected behavior**
Plot should update with the new values, showing the first bufmax values.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - OS: Ubuntu 22.04
 - Firefox 119.0 (64-bit)

**Additional context**
This issue is not present in the older LGSInnovations code.

**Comment by maihde** [comment]
Thanks @EighthOctave we will take a look, if you need a fix urgently for a operational system, please let me know and we can coordinate further. Otherwise, we will try to get a fix out in the next release.

**Comment by maihde** [comment]
@EighthOctave I have fix this and it will be included in version `3.1.1`.  The changes are very simple, so you can manually backport the fix if necessary.

**Comment by EighthOctave** [comment]
Fantastic! Thanks so much!
